data:
  name:  synthetic #SMAP #MSL
  category: NoiseLevel20 #NoiseLevel10
            #
  data_dir: './data/signature_matrix/'
  data_label: './data/labeled_anomalies/'
  batch_size: 5
  trajectory_steps: 10000


synthetic:
  ts_lengths: 20000
  num_vars: 30
  noise_level: 20
  noise_variance: 1
  noise_mean: 0
  output_dir: './data/time_series/synthetic/'


signature_matrix:
  input_dir: './data/time_series/'
  output_dir: './data/signature_matrix/'
  time_step: 10
  window: 60 #10 #30 #60


model:
  checkpoint_dir: '/checkpoints/NoiseLevel20'
  checkpoint_name: weights
  result_dir: results
  load_checkpoint: 20

  exp_name: default
  learning_rate: 3e-4
  weight_decay: 0.05

  num_workers: 2
  epoch: 10
  inner_iter: 5

  device: 'cuda'
  save_model: True

hyperparameter:
  lamda: 1
  error_limit: 0.0001
  beta: 1
  gama: 0.005


metric:
  auroc: True
  misclassifications: False
  visualisation: False