signature_matrix:
  input_dir: '/content/RCLED/data/time_series/' #'./data/time_series/'  
  output_dir: './data/signature_matrix/'
  time_step: 10 # 2 (SMAP) 10(synthetic)
  windows: [5, 15, 30]
  
data:
  name:  synthetic #synthetic #SMAP #MSL
  category: NoiseLevel5 #NoiseLevel5 #NoiseLevel10
                #NoiseLevel20
  data_dir: './data/signature_matrix/'
  data_label: './data/labeled_anomalies/'
  batch_size: 1
  trajectory_steps: 10000


synthetic:
  ts_lengths: 20000
  num_vars: 30
  noise_level: 5 # 5% 10% 15%
  noise_variance: 1
  noise_mean: 0
  output_dir: './data/time_series/synthetic/'


model:
  checkpoint_dir: './checkpoints/'
  checkpoint_name: weights
  result_dir: './results/'
  load_checkpoint: 20

  learning_rate: 0.002

  num_workers: 2
  epoch: 20
  inner_iter: 1

  device: 'cuda'
  save_model: True

hyperparameter:
  lamda: 0.001
  error_limit: 0.0001
  beta: 1
  gama: 0.005


metric:
  auroc: True
  visualisation: False