signature_matrix:
  input_dir: '/content/drive/MyDrive/RCLED/datasets/' #'./data/time_series/'  
  output_dir: './data/signature_matrix/'
  time_step: 10 # 2 (SMAP) 10(synthetic)
  windows: [10, 30, 60]
  
data:
  name:  SMAP #synthetic #SMAP #MSL
  category: A-1 #NoiseLevel5 #NoiseLevel10
                #NoiseLevel20
  data_dir: './data/signature_matrix/'
  data_label: './data/labeled_anomalies/'
  batch_size: 5
  trajectory_steps: 10000


synthetic:
  ts_lengths: 20000
  num_vars: 30
  noise_level: 5 # 5% 10% 15%
  noise_variance: 1
  noise_mean: 0
  output_dir: './data/time_series/synthetic/'


model:
  checkpoint_dir: './checkpoints/'
  checkpoint_name: weights
  result_dir: './results/'
  load_checkpoint: 10

  learning_rate: 0.001

  num_workers: 2
  epoch: 100
  inner_iter: 1

  device: 'cuda'
  save_model: True

hyperparameters:
  lamda: 0.001
  error_limit: 0.0001
  beta: 1
  gama: 0.005


metric:
  auroc: True
  misclassifications: False
  visualisation: False